[package]
name = "workshop"
version = "0.1.0"
edition = "2023_01"

[[target.starknet-contract]]
casm = true
build-external-contracts = ["kill_switch::KillSwitch"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.8.0"
snforge_std = "0.29.0"
kill_switch = {git = "https://github.com/starknet-edu/kill-switch.git" }

[dev-dependencies]
cairo_test = "2.8.0"

[profile.dev.scripts]
test="snforge test"


